# Generated by Django 5.2.1 on 2025-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'TO DO'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída')], default='pending', max_length=15),
        ),
    ]
