# Generated by Django 5.2.1 on 2025-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_completed_by_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('compras', 'Compras'), ('limpeza', 'Limpeza'), ('geral', 'Geral')], default='geral', max_length=20),
        ),
    ]
