# Generated by Django 5.2.1 on 2025-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('compras', 'Compras'), ('limpeza', 'Limpeza'), ('manutenção', 'Manutenção'), ('geral', 'Geral')], default='geral', max_length=20),
        ),
    ]
