# Generated by Django 5.2.1 on 2025-05-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('comida', 'Comida'), ('agua', 'Água'), ('luz', 'Luz'), ('gas', 'Gás'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
