# Generated by Django 5.2.1 on 2025-05-16 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='members',
        ),
        migrations.AlterField(
            model_name='house',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa_administrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HouseMembership',
        ),
    ]
