# Generated by Django 5.2.1 on 2025-05-16 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_remove_house_members_alter_house_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Administrador'), ('ROOMIE', 'Roomie')], default='ROOMIE', max_length=10, verbose_name='Tipo de Utilizador')),
                ('profile_picture', models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_entrada', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='houses.house')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
